import js from '@eslint/js';
import { defineConfig } from 'eslint/config';
import prettier from 'eslint-config-prettier';
import tseslint from 'typescript-eslint';

/**
 * Architecture boundaries.
 *
 * The layering defined in ARCHITECTURE.md is not a convention — it is a
 * compile-time contract. Each entry below states which layers a file is
 * *forbidden* to import, so a violation fails `pnpm lint` instead of being
 * caught (or missed) in review.
 *
 * Allowed direction of dependency:
 *   Controller -> Use Case -> Workflow -> Agent -> Repository -> Service
 */
const LAYER = {
  controllers: 'src/controllers/**/*.ts',
  useCases: 'src/use-cases/**/*.ts',
  workflows: 'src/workflows/**/*.ts',
  agents: 'src/agents/**/*.ts',
  repositories: 'src/repositories/**/*.ts',
  services: 'src/services/**/*.ts',
  database: 'src/database/**/*.ts',
};

/** Import patterns that identify each layer, used by `no-restricted-imports`. */
const IMPORTS = {
  controllers: '**/controllers/**',
  useCases: '**/use-cases/**',
  workflows: '**/workflows/**',
  agents: '**/agents/**',
  repositories: '**/repositories/**',
  services: '**/services/**',
  prisma: ['@prisma/client', '@prisma/client/**', '@prisma/adapter-*', '**/database/generated/**'],
  network: ['node:http', 'node:https', 'node:net', 'undici', 'axios'],
  filesystem: ['node:fs', 'node:fs/*', 'node:child_process'],
};

/**
 * @param {Array<{ patterns: string[], message: string }>} groups
 * @returns {import('eslint').Linter.RulesRecord}
 */
const forbidImports = (groups) => ({
  'no-restricted-imports': [
    'error',
    { patterns: groups.map(({ patterns, message }) => ({ group: patterns, message })) },
  ],
});

export default defineConfig([
  {
    ignores: [
      'dist/**',
      // Generated by `prisma generate`; never hand-edited, never linted.
      'src/database/generated/**',
      'output/**',
      'coverage/**',
      'node_modules/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,

  {
    languageOptions: {
      parserOptions: {
        // Tooling configuration files live outside tsconfig's `include`, so the
        // default project is what lets them be linted at all.
        projectService: { allowDefaultProject: ['*.js'] },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Logging goes through the Logger abstraction so every line carries a
      // correlation id and can be persisted by LogRepository.
      'no-console': 'error',
      eqeqeq: ['error', 'always'],
      'no-param-reassign': 'error',
      'prefer-const': 'error',
      '@typescript-eslint/explicit-member-accessibility': [
        'error',
        { accessibility: 'explicit', overrides: { constructors: 'no-public' } },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // Configuration is read once, validated once, and injected everywhere else.
      'no-restricted-properties': [
        'error',
        {
          object: 'process',
          property: 'env',
          message: 'Read environment variables only in src/config, then inject the typed config.',
        },
      ],
    },
  },

  // --- Layer: Controller -----------------------------------------------------
  {
    files: [LAYER.controllers],
    rules: forbidImports([
      {
        patterns: [
          IMPORTS.workflows,
          IMPORTS.agents,
          IMPORTS.repositories,
          IMPORTS.services,
          ...IMPORTS.prisma,
        ],
        message: 'Controllers may only depend on use-cases. See ARCHITECTURE.md.',
      },
    ]),
  },

  // --- Layer: Use Case -------------------------------------------------------
  {
    files: [LAYER.useCases],
    rules: forbidImports([
      {
        patterns: [IMPORTS.agents, IMPORTS.services, IMPORTS.controllers, ...IMPORTS.prisma],
        message: 'Use-cases orchestrate workflows and repositories only. See ARCHITECTURE.md.',
      },
    ]),
  },

  // --- Layer: Workflow -------------------------------------------------------
  {
    files: [LAYER.workflows],
    rules: forbidImports([
      {
        patterns: [
          IMPORTS.services,
          IMPORTS.controllers,
          IMPORTS.useCases,
          ...IMPORTS.prisma,
          ...IMPORTS.network,
        ],
        message:
          'Workflows orchestrate agents and persist state through repositories; they never touch external systems directly.',
      },
    ]),
  },

  // --- Layer: Agent ----------------------------------------------------------
  {
    files: [LAYER.agents],
    rules: forbidImports([
      {
        // Sibling imports are relative (`./topic.agent.js`), so they need their
        // own pattern — `**/agents/**` never matches them.
        patterns: ['./*.agent.js', './*.agent'],
        message: 'Agents never call other agents. Let the workflow coordinate them.',
      },
      {
        patterns: [
          IMPORTS.agents,
          IMPORTS.workflows,
          IMPORTS.useCases,
          IMPORTS.controllers,
          ...IMPORTS.prisma,
          ...IMPORTS.network,
          ...IMPORTS.filesystem,
        ],
        message:
          'Agents hold business logic only. They never call other agents and never touch infrastructure directly.',
      },
    ]),
  },

  // --- Layer: Repository -----------------------------------------------------
  {
    files: [LAYER.repositories],
    rules: forbidImports([
      {
        patterns: [
          IMPORTS.services,
          IMPORTS.agents,
          IMPORTS.workflows,
          IMPORTS.useCases,
          IMPORTS.controllers,
          ...IMPORTS.network,
          ...IMPORTS.filesystem,
        ],
        message: 'Repositories do CRUD against PostgreSQL. Nothing else.',
      },
    ]),
  },

  // --- Layer: Service --------------------------------------------------------
  {
    files: [LAYER.services],
    rules: forbidImports([
      {
        patterns: [
          IMPORTS.repositories,
          IMPORTS.agents,
          IMPORTS.workflows,
          IMPORTS.useCases,
          IMPORTS.controllers,
          ...IMPORTS.prisma,
        ],
        message: 'Services integrate exactly one external system and hold no business logic.',
      },
    ]),
  },

  // --- Layer: Database -------------------------------------------------------
  // The only place besides repositories allowed to see the generated client.
  {
    files: [LAYER.database],
    rules: forbidImports([
      {
        patterns: [
          IMPORTS.repositories,
          IMPORTS.agents,
          IMPORTS.workflows,
          IMPORTS.useCases,
          IMPORTS.controllers,
          IMPORTS.services,
        ],
        message: 'The database module owns the Prisma connection and nothing else.',
      },
    ]),
  },

  // --- Composition root & configuration --------------------------------------
  // `src/main.ts` and `src/composition-root.ts` wire every layer together, and
  // `src/config` is the single place allowed to read `process.env`.
  {
    files: ['src/main.ts', 'src/composition-root.ts', 'src/config/**/*.ts'],
    rules: {
      'no-restricted-imports': 'off',
      'no-restricted-properties': 'off',
    },
  },

  // --- Tests -----------------------------------------------------------------
  {
    files: ['tests/**/*.ts'],
    rules: {
      'no-restricted-imports': 'off',
      'no-restricted-properties': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/unbound-method': 'off',
    },
  },

  // --- Tooling configuration files -------------------------------------------
  {
    files: ['*.config.js', '*.config.ts', 'prisma.config.ts'],
    rules: {
      'no-restricted-properties': 'off',
      'no-restricted-imports': 'off',
    },
  },

  prettier,
]);
