// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/credentials" | "/dashboard" | "/login" | "/logs" | "/schedules" | "/uploads" | "/workflows" | "/workflows/[runId]"
type AppRouteHandlerRoutes = "/api/auth/login" | "/api/auth/logout" | "/api/credentials" | "/api/credentials/[id]" | "/api/credentials/capture" | "/api/credentials/capture/[id]" | "/api/media/[...path]" | "/api/runs" | "/api/runs/[runId]" | "/api/runs/[runId]/images/bulk" | "/api/runs/[runId]/publish" | "/api/runs/[runId]/resume" | "/api/runs/[runId]/scenes/[scene]/image" | "/api/runs/[runId]/steps/[step]" | "/api/runs/[runId]/stream" | "/api/schedules" | "/api/schedules/[id]" | "/api/speech/preview" | "/api/topics/suggest" | "/api/uploads" | "/api/uploads/[id]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/credentials": {}
  "/api/credentials/[id]": { "id": string; }
  "/api/credentials/capture": {}
  "/api/credentials/capture/[id]": { "id": string; }
  "/api/media/[...path]": { "path": string[]; }
  "/api/runs": {}
  "/api/runs/[runId]": { "runId": string; }
  "/api/runs/[runId]/images/bulk": { "runId": string; }
  "/api/runs/[runId]/publish": { "runId": string; }
  "/api/runs/[runId]/resume": { "runId": string; }
  "/api/runs/[runId]/scenes/[scene]/image": { "runId": string; "scene": string; }
  "/api/runs/[runId]/steps/[step]": { "runId": string; "step": string; }
  "/api/runs/[runId]/stream": { "runId": string; }
  "/api/schedules": {}
  "/api/schedules/[id]": { "id": string; }
  "/api/speech/preview": {}
  "/api/topics/suggest": {}
  "/api/uploads": {}
  "/api/uploads/[id]": { "id": string; }
  "/credentials": {}
  "/dashboard": {}
  "/login": {}
  "/logs": {}
  "/schedules": {}
  "/uploads": {}
  "/workflows": {}
  "/workflows/[runId]": { "runId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
