// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(app)/credentials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credentials">> = Specific
  const handler = {} as typeof import("../../app/(app)/credentials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logs">> = Specific
  const handler = {} as typeof import("../../app/(app)/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/schedules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/schedules">> = Specific
  const handler = {} as typeof import("../../app/(app)/schedules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/uploads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/uploads">> = Specific
  const handler = {} as typeof import("../../app/(app)/uploads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/workflows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflows">> = Specific
  const handler = {} as typeof import("../../app/(app)/workflows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/workflows/[runId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflows/[runId]">> = Specific
  const handler = {} as typeof import("../../app/workflows/[runId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/credentials/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/credentials/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/credentials/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/credentials/capture/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/credentials/capture/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/credentials/capture/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/credentials/capture/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/credentials/capture">> = Specific
  const handler = {} as typeof import("../../app/api/credentials/capture/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/credentials/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/credentials">> = Specific
  const handler = {} as typeof import("../../app/api/credentials/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/media/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/[...path]">> = Specific
  const handler = {} as typeof import("../../app/api/media/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[runId]/images/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[runId]/images/bulk">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[runId]/images/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[runId]/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[runId]/publish">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[runId]/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[runId]/resume/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[runId]/resume">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[runId]/resume/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[runId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[runId]">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[runId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[runId]/scenes/[scene]/image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[runId]/scenes/[scene]/image">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[runId]/scenes/[scene]/image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[runId]/steps/[step]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[runId]/steps/[step]">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[runId]/steps/[step]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[runId]/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[runId]/stream">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[runId]/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs">> = Specific
  const handler = {} as typeof import("../../app/api/runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schedules/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schedules/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/schedules/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schedules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schedules">> = Specific
  const handler = {} as typeof import("../../app/api/schedules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/speech/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/speech/preview">> = Specific
  const handler = {} as typeof import("../../app/api/speech/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/topics/suggest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/topics/suggest">> = Specific
  const handler = {} as typeof import("../../app/api/topics/suggest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/uploads/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploads/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/uploads/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/uploads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploads">> = Specific
  const handler = {} as typeof import("../../app/api/uploads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
